meta_name: "goTogether"
meta_title: "goTogether: Connecting Events, Friends, and Experiences"
meta_description: "Discover, plan, and share events effortlessly with goTogether. Connect with friends, explore exciting activities, and make memories together. Simplify your event planning experience with our all-in-one app. Join the GoTogether community today"
meta_image: "resized-goTogether.png" # should exist in `app/assets/images/`
